# Generated by Django 3.1.7 on 2021-05-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BussinesIncubator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klien', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, help_text='Masukkan keterangan sampel', null=True)),
                ('keterangan', models.TextField(blank=True, help_text='Masukkan keterangan sampel', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True, help_text='Masukkan keterangan topik konsultasi', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Mohon memasukkan nama sample sesuai format (ex: Biji Kakao)', max_length=200)),
                ('sni', models.CharField(help_text='Mohon memasukkan no. SNI yang benar sesuai format (ex: SNI 2323 : 2008', max_length=100, verbose_name='Nomor SNI')),
                ('kategori', models.CharField(choices=[('p', 'Pertanian'), ('P', 'Pangan'), ('m', 'Mineral'), ('M', 'Maritim'), ('A', 'Agro'), ('X', 'Lain-Lain')], default='X', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceIndeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_pelayanan', models.IntegerField(default=2020)),
                ('indeks_kepuasan', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True, help_text='Masukkan keterangan pelatihan', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True, help_text='Masukkan keterangan sampel', null=True)),
                ('sample', models.ManyToManyField(help_text='Pilih jenis layanan', to='home.Sample')),
            ],
        ),
    ]
