# Generated by Django 3.1.7 on 2021-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindeks',
            name='indeks_kepuasan',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
