# Generated by Django 3.1.7 on 2021-04-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_tanggal_publikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndeksKepuasanPelayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_pelayanan', models.IntegerField(max_length=4)),
                ('indeks_kepuasan', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
