# Generated by Django 3.1.7 on 2021-05-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210519_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceindeks',
            options={'ordering': ['tahun_pelayanan']},
        ),
    ]
