# Generated by Django 3.1.7 on 2021-05-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210519_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceindeks',
            options={'ordering': ['-tahun_pelayanan']},
        ),
        migrations.AlterField(
            model_name='sample',
            name='sni',
            field=models.CharField(default='SNI - ', help_text='Mohon memasukkan no. SNI yang benar sesuai format (ex: SNI 2323 : 2008', max_length=100, verbose_name='Nomor SNI'),
        ),
    ]
