# Generated by Django 3.1.7 on 2021-04-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210407_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indekskepuasanpelayanan',
            name='indeks_kepuasan',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='indekskepuasanpelayanan',
            name='tahun_pelayanan',
            field=models.IntegerField(default=2020, max_length=4),
        ),
    ]
