# Generated by Django 3.1.7 on 2021-04-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210407_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indekskepuasanpelayanan',
            name='tahun_pelayanan',
            field=models.IntegerField(default=2020),
        ),
    ]
