# Generated by Django 3.1.7 on 2021-05-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_calibration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, unique=True)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bussinesincubator',
            name='klien',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='calibration',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='kategori',
            field=models.CharField(choices=[('p', 'Pertanian'), ('P', 'Pangan'), ('m', 'Mineral'), ('M', 'Maritim'), ('X', 'Lain-Lain')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nama',
            field=models.CharField(help_text='Mohon memasukkan nama sample sesuai format (ex: Biji Kakao)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
